"""
Shared idle-playlist generation logic, used by both:
  - the manual POST /api/v1/avatars/{id}/idle-playlist endpoint
  - the automatic trigger on chat-session open (see app/websocket.py)

Point of this module: an avatar's idle playlist is a one-time, cacheable
asset (see idle_playlist_urls on the Avatar model) — once generated it's
just replayed as plain <video> elements client-side, at zero GPU cost.
Regenerating it on every chat open would be wasteful and, worse, would
race the live chat pipeline for the GPU exactly the way that broke things
earlier in this session (see app/services/gpu_lock.py). So the real job
here is: generate once, reuse forever, and never kick off a redundant
concurrent generation for the same avatar.
"""
import logging
from pathlib import Path

from sqlalchemy import select

from app.database import AsyncSessionLocal
from app.models import Avatar
from app.services.hallo2_animator import MAX_PLAYLIST_SEGMENTS, hallo2_animator
from app.services.storage import resolve_local_image, storage_service

logger = logging.getLogger(__name__)

# Avatar IDs currently generating a playlist — guards against two sessions
# opening for the same avatar at once (or a manual call overlapping an
# auto-triggered one) both kicking off their own redundant Hallo2 batch.
_in_progress: set[str] = set()


def needs_idle_playlist(avatar: Avatar) -> bool:
    urls = avatar.idle_playlist_urls
    return not urls or len(urls) < MAX_PLAYLIST_SEGMENTS


def is_generation_in_progress(avatar_id: str) -> bool:
    return avatar_id in _in_progress


async def ensure_idle_playlist(avatar_id: str, num_segments: int = MAX_PLAYLIST_SEGMENTS) -> list[str]:
    """
    Generate and persist the idle playlist for `avatar_id`, unless one
    already exists (or is already being generated by someone else right
    now). Opens its own DB session so it's safe to call from a
    fire-and-forget background task as well as from a request handler.

    Returns the resulting idle_playlist_urls (existing or freshly
    generated). Returns [] if generation was skipped because another call
    is already in flight for this avatar — the in-flight call owns the
    result.
    """
    if avatar_id in _in_progress:
        logger.info(f"Idle playlist generation already in progress for avatar {avatar_id}, skipping")
        return []

    async with AsyncSessionLocal() as db:
        result = await db.execute(select(Avatar).where(Avatar.id == avatar_id))
        avatar = result.scalar_one_or_none()
        if not avatar:
            return []
        if not needs_idle_playlist(avatar):
            return avatar.idle_playlist_urls

        _in_progress.add(avatar_id)
        try:
            # Top up, don't redo: keep whatever already rendered and only
            # generate the gap. Segments already succeeded and are already
            # uploaded/served — nothing to gain from paying their ~4-5min
            # GPU cost again, and every minute spent redoing them is a
            # minute this avatar's idle playlist stays short (or a minute
            # of avoidable GPU contention with a live chat render).
            existing_urls = list(avatar.idle_playlist_urls or [])
            remaining = num_segments - len(existing_urls)
            if remaining <= 0:
                return existing_urls

            local_image = await resolve_local_image(avatar.id, avatar.s3_key)
            import tempfile
            work_dir = Path(tempfile.gettempdir()) / f"{avatar_id}_idle_playlist"

            try:
                local_segments = await hallo2_animator.generate_idle_playlist(
                    local_image, str(work_dir), num_segments=remaining, seed_offset=len(existing_urls),
                )
                if not local_segments and not existing_urls:
                    logger.error(f"Idle playlist generation produced no segments for avatar {avatar_id}")
                    return []

                new_urls = []
                for i, local_path in enumerate(local_segments):
                    idx = len(existing_urls) + i
                    video_key = f"avatars/{avatar_id}/idle_playlist/segment_{idx}.mp4"
                    await storage_service.upload_file(
                        Path(local_path).read_bytes(), video_key, content_type="video/mp4"
                    )
                    new_urls.append(await storage_service.serving_url(video_key))
            finally:
                import shutil
                shutil.rmtree(work_dir, ignore_errors=True)

            playlist_urls = existing_urls + new_urls
            avatar.idle_playlist_urls = playlist_urls
            await db.commit()
            logger.info(
                f"Idle playlist for avatar {avatar_id}: {len(existing_urls)} kept + "
                f"{len(new_urls)} new = {len(playlist_urls)} segments"
            )
            return playlist_urls
        except Exception as e:
            await db.rollback()
            logger.error(f"Idle playlist generation failed for avatar {avatar_id}: {e}")
            return []
        finally:
            _in_progress.discard(avatar_id)
